# Generated by Django 4.2.4 on 2023-10-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo_post',
            field=models.CharField(default='Post de {{ post.autor.first_name }}', max_length=255),
        ),
    ]
