# Generated by Django 4.2.4 on 2023-11-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_e_d_e_g_e_l_e_m_e_o'),
        ('Usuarios', '0003_post_titulo_post'),
    ]

    operations = [
    ]
